# Generated by Django 2.2 on 2019-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('tell_about', models.CharField(max_length=250)),
                ('detail_heading', models.CharField(max_length=250)),
                ('personal_detail', models.CharField(max_length=1000)),
                ('view', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000)),
                ('quality_product', models.CharField(max_length=1000)),
                ('tool_expertness_heading', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_Image', models.ImageField(upload_to='images/')),
                ('user_image', models.ImageField(upload_to='images/')),
                ('user_name', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=40)),
                ('heart_tag', models.CharField(max_length=250)),
                ('bubble_tag', models.CharField(max_length=250)),
                ('image_title', models.CharField(max_length=250)),
                ('image_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('view_button', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('number_of_product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomeCategoryWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(upload_to='images/')),
                ('category_title', models.CharField(max_length=250)),
                ('category_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('views', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_description', models.CharField(max_length=10000)),
                ('blog_view_button', models.CharField(max_length=500)),
                ('quotes', models.CharField(max_length=10000)),
                ('sample_image', models.ImageField(upload_to='images/')),
                ('sample_image2', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomeNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=250)),
                ('subcribe', models.CharField(max_length=250)),
                ('subcribe_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomePopularPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('post_time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BlogHomeSearchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSingleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
                ('reply', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSingleLeaveComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_heading', models.CharField(max_length=250)),
                ('enter_name', models.CharField(max_length=250)),
                ('enter_mail', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('messege', models.CharField(max_length=1000)),
                ('post_comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSinglePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('direction', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSingleTagsCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=250)),
                ('fashion', models.CharField(max_length=250)),
                ('Architecture', models.CharField(max_length=250)),
                ('Food', models.CharField(max_length=250)),
                ('Lifestyle', models.CharField(max_length=250)),
                ('Art', models.CharField(max_length=250)),
                ('Adventure', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ChosePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.IntegerField()),
                ('package_name', models.CharField(max_length=250)),
                ('package_title', models.CharField(max_length=250)),
                ('package_one', models.CharField(max_length=250)),
                ('package_two', models.CharField(max_length=250)),
                ('package_three', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('buy', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('feedback', models.CharField(max_length=500)),
                ('client_name', models.CharField(max_length=250)),
                ('client_post', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_heading', models.CharField(max_length=500)),
                ('service_detail', models.CharField(max_length=500)),
                ('feature_heading', models.CharField(max_length=500)),
                ('feature_detail', models.CharField(max_length=500)),
                ('clientfeedback_heading', models.CharField(max_length=500)),
                ('clientfeedback_detail', models.CharField(max_length=500)),
                ('plan_heading', models.CharField(max_length=500)),
                ('plan_detail', models.CharField(max_length=500)),
                ('blog_heading', models.CharField(max_length=500)),
                ('blog_detail', models.CharField(max_length=500)),
                ('qualification_heading', models.CharField(max_length=250)),
                ('qualification_detail', models.CharField(max_length=250)),
                ('asked_question_heading', models.CharField(max_length=250)),
                ('asked_question_detail', models.CharField(max_length=500)),
                ('popular_post_heading', models.CharField(max_length=250)),
                ('post_category_heading', models.CharField(max_length=250)),
                ('blog_comment_heading', models.CharField(max_length=250)),
                ('blog_single_tag_heading', models.CharField(max_length=250)),
                ('page_sample_heading', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myself', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=500)),
                ('discover', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('previous_img', models.ImageField(upload_to='images/')),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
                ('result', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_tag', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicesComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_services', models.IntegerField()),
                ('services_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ToolExpertness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_expert_percentage', models.CharField(max_length=250)),
                ('width', models.CharField(max_length=200)),
            ],
        ),
    ]
