# Generated by Django 2.2 on 2019-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='quality_product',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
