# Generated by Django 2.2 on 2019-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190423_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choseplan',
            old_name='package_one',
            new_name='packages',
        ),
        migrations.RemoveField(
            model_name='choseplan',
            name='package_three',
        ),
        migrations.RemoveField(
            model_name='choseplan',
            name='package_two',
        ),
    ]
