# Generated by Django 2.2 on 2019-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190423_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_email', models.EmailField(max_length=120)),
            ],
        ),
    ]
