# Generated by Django 2.2 on 2019-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_news_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFormAddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_address', models.CharField(max_length=250)),
                ('simple_address', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
