# Generated by Django 2.2 on 2019-04-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190423_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientFeedback',
            new_name='ClientFeedbackAboutMe',
        ),
    ]
