# Generated by Django 2.2 on 2019-04-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190423_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='tool_expertness_heading',
        ),
    ]
