# Generated by Django 2.2 on 2019-04-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_about_tool_expertness_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heading',
        ),
    ]
