# Generated by Django 2.2 on 2019-04-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_subs',
            new_name='NewsSubscription',
        ),
    ]
